### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by WHK102** [WHK102/wss#2]
Desde alguna distribución de GNU/Linux, cuando se realiza un escaneo de puertos en algunos casos python arroja el siguiente mensaje:

```
- Filtro 1/1: Filtrando puertos ...
    -> 1/4 : x.x.x.x ...
        80 Abierto.
        443 Abierto.
        Escaneando puerto: 65534 ...libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
Abortado (`core' generado)
```

He buscado en innumerables lugares y he llegado a la conclusión de que es un bug de la compilación de python3, esto se reproduce en Ubuntu 18.04 y CentOS 7 a traves de python 3.6.

Por el momento la solución es la incorporación manual de la librería de la siguiente manera:

`$ LD_PRELOAD=libgcc_s.so.1 python3 wss.py --host ...`

Algunas referencias:

- https://bugs.python.org/issue18748
- https://bugs.launchpad.net/ubuntu/+source/gcc-3.3/+bug/40285

De todas maneras es un corporamiento extraño ya que existen otros módulos que hacen uso de múltiples hilos de proceso pero solo el filtro de puertos provoca ese error, por ejemplo al intentar hacer un escaneo de pruebas hacia elhacker.net:

`python3 wss.py --host elhacker.net -m 2 -f 0`

Pero en muchos otros dominios este problema no ocurre.

Problema comprobado en Ubuntu 18.04 LTS:

```
$ python3 --version
Python 3.6.8
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

Y en CentOS 7:

```
$ python3 --version
Python 3.6.8
$ rpm -q centos-release
centos-release-7-6.1810.2.el7.centos.x86_64
```

Cuando encuentre una respuesta y una solución más certera cerraré este problema.

**Comment by WHK102** [comment]
El problema se debe cuando se sobrepasa la cantidad máxima de hilos de proceso establecidos por la seguridad en Linux ( `/etc/security/limits.conf` ). Se ha rebajado la cantidad de threads a 500.

**Comment by WHK102** [comment]
Se soluciona bajando la cantidad de hilos de proceso. He agregado un filtro de reemplazo que utiliza solo 3 hilos utilizando paquetes tcp a bajo nivel.

**Comment by santosadrian** [comment]
user@DESKTOP-GIEE17U:~$ ftpknocker --port 2121 136.32.0.0/11
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted (core dumped)

user@DESKTOP-GIEE17U:~$ LD_PRELOAD=libgcc_s.so.1 ftpknocker --port 2121 136.32.0.0/11
Segmentation fault (core dumped)

alguien tiene la solucion?

**Comment by WHK102** [comment]
Hola, eso sucede cuando python excede la cantidad máxima de threads soportados por el sistema operativo, lamentablemente es un mensaje de error generado por el interpretador de python, actualmente python no es capaz de detectar y controlar este valor del lado del script. He intentado solucionar esto rebajando la cantidad de threads en mi script, porque por lo que veo estás consultando por otro proyecto pero del mismo problema.

Realmente python no necesita la precarga de la librería libgcc pero si se hace necesario cuando excedes un cierto límite de threads, pero cuando superas ese segundo tope de límte simplemente python deja de funcionar.

Hay maneras de averiguar el límite actual de threads diponibles del sistema pero en cada sistema operativo se hace de manera distinta, por lo cual una de las pocas soluciones que existen es realizar una integración a bajo nivel fuera del control de python, talves con alguna librería para cpython, la otra solución es simplemente disminuir la cantidad de hilos. Cuando usas una máquina virtual esto da un problema adicional ya que debes ajustar la cantidad de threads limitados al sistema de virtualización. En este tipo de casos Linux tiene un mejor manejo de hilos que Windows y es mas eficiente.

En otros lenguajes como Java he tenido limitancias similares pero por lo menos el control está mucho mejor diseñado y puedes utilizar las pilas de manera dinámica según la carga de cpu y la cantidad de hilos disponibles ya que te limita a usar valores mas bajos de lo permitido por el sistema, pero lamentablemente python carece de este tipo de controles.

Espero que te haya servido de algo esta información.

Saludos.

**Comment by santosadrian** [comment]
Muchas gracias por tan detallada respuesta.
